id: P3378BE29
initial_creation_type: input
source_metadata:
  title: Seventh Dalai Lama Series
  language: bo
  description: 'Texts by the Seventh Dalai Lama, Kalzang Gyatso (skal bzang rgya mtsho,
    1708–1757):'
  volume:
    917b64c8a05840b2b05bd16016a7b025:
      title: 'Rain of Accomplishments: A Song that Incorporates the Four Mindfulnesses
        from an Instruction on the View of the Middle Way'
      parent: Songs
created_at: '2022-03-01T01:30:32.331618'
last_modified_at: '2022-03-01T01:30:32.331620'
